name: GH Stats

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Profile Gist with Github Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npx github-stats-box
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: c59f2e715f3b894a3c44bee22731234c
          ALL_COMMITS: false
          K_FORMAT: false