name: RSS and Activity [EN]

on:
  schedule:
    - cron: "30 3 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Markdown template
        uses: lowlighter/metrics@latest
        with:
          # GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Configure template type
          template: markdown
          filename: docs/translations/README_EN.md
          markdown: docs/template/README_TEMPLATE_EN.md

          # Options
          user: SmithyVL
          base: ""
          config_timezone: Europe/Kirov
          plugin_activity: yes
          plugin_activity_filter: all
          plugin_activity_timestamps: yes
          plugin_rss: yes
          plugin_rss_source: https://feeds.feedblitz.com/baeldung
          plugin_rss_limit: 5